Repository devops2024-group-e/itu-minitwit, pull requests merged in 2024-02, with the labels that each got.

#1 Add dev-container
  .devcontainer/devcontainer.json
  .gitignore
  README.md
  flag_tool
  minitwit.py
  tmp/minitwit.db
Labels: documentation, enhancement

#2 Fix tests trying to assert on binary data
  Makefile
  minitwit_tests.py
Labels: bug, enhancement

#3 Change `python` command calls to `python3`🔢
  control.sh
Labels: enhancement

#5 Add db file from the server
  .gitignore
  tmp/minitwit.db
Labels: enhancement

#6 Add issue log about how to fix auth for WSL and MacOS
  docs/issues/github-auth.md
Labels: enhancement

#17 Add log of what we did in week 1
  docs/log.md
Labels: documentation

#18 Convert login page from python to C#
  .gitignore
  docs/refactor/login.md
  itu_new_minitwit/Model/UserCredential.cs
  itu_new_minitwit/Pages/Login.cshtml
  itu_new_minitwit/Pages/Login.cshtml.cs
  itu_new_minitwit/Program.cs
  minitwit_tests.py
Labels: enhancement

#20 Convert Register page from python ➡️ C#
  docs/refactor/register.md
  itu_new_minitwit/Model/User.cs
  itu_new_minitwit/Pages/Register.cshtml
  itu_new_minitwit/Pages/Register.cshtml.cs
  itu_new_minitwit/Program.cs
Labels: documentation, enhancement

#21 Add `CODEOWNERS` file with dev team 💪 👮
  CODEOWNERS
Labels: documentation

#46 Add composite primary key to followers table
  Minitwit/Controllers/TimelineController.cs
  Minitwit/MinitwitContext.cs
  Minitwit/Models/Follower.cs
  schema.sql
Labels: documentation, enhancement

#48 Get connectionstring from environment variables
  Minitwit/Program.cs
  Minitwit/appsettings.Development.json
  Minitwit/appsettings.json
Labels: enhancement

#47 Use dotnet Entity Framework to create the Database 🏗️
  Makefile
  control.sh
  minitwit.py
Labels: enhancement

#54 Feature/basic api install
  MinitwitSimulatorAPI/Controllers/LoginController.cs
  MinitwitSimulatorAPI/Controllers/LogoutController.cs
  MinitwitSimulatorAPI/Controllers/RegisterController.cs
  MinitwitSimulatorAPI/Controllers/TimelineController.cs
  MinitwitSimulatorAPI/MinitwitSimulatorAPI.csproj
  MinitwitSimulatorAPI/Models/Follower.cs
  MinitwitSimulatorAPI/Models/Message.cs
  MinitwitSimulatorAPI/Models/MessageAuthor.cs
  MinitwitSimulatorAPI/Models/MinitwitContext.cs
  MinitwitSimulatorAPI/Models/User.cs
  MinitwitSimulatorAPI/Program.cs
  MinitwitSimulatorAPI/Properties/launchSettings.json
  MinitwitSimulatorAPI/Test/README_Testing.md
  MinitwitSimulatorAPI/Test/minitwit_scenario.csv
  MinitwitSimulatorAPI/Test/minitwit_sim_api.py
  MinitwitSimulatorAPI/Test/minitwit_simulator.py
  MinitwitSimulatorAPI/Test/schema.sql
  MinitwitSimulatorAPI/Utils/GravatarHtmlHelper.cs
  MinitwitSimulatorAPI/Utils/PasswordHash.cs
  MinitwitSimulatorAPI/Utils/TempdataExtensions.cs
  MinitwitSimulatorAPI/ViewModels/ErrorViewModel.cs
  MinitwitSimulatorAPI/ViewModels/LoginViewModel.cs
  MinitwitSimulatorAPI/ViewModels/PublicTimelineViewModel.cs
  MinitwitSimulatorAPI/ViewModels/RegisterViewModel.cs
  MinitwitSimulatorAPI/ViewModels/TimelineViewModel.cs
  MinitwitSimulatorAPI/appsettings.Development.json
  MinitwitSimulatorAPI/appsettings.json
  minitwit_sim_api_test.py
Labels: documentation, enhancement

#63 Feature/vagrant setup
  Vagrantfile
Labels: documentation, enhancement
