Repository devops2024-group-e/itu-minitwit, pull requests merged in 2024-03, with the labels that each got.

#78 Make Simulator pass all tests ✅
  Minitwit/MinitwitContext.cs
  Minitwit/Models/Latest.cs
  MinitwitSimulatorAPI/Controllers/LatestController.cs
  MinitwitSimulatorAPI/Controllers/RegisterController.cs
  MinitwitSimulatorAPI/Controllers/TimelineController.cs
  MinitwitSimulatorAPI/MinitwitContext.cs
  MinitwitSimulatorAPI/Models/Latest.cs
  MinitwitSimulatorAPI/Models/RegisterUser.cs
  docker-composelocal.yaml
  minitwit_sim_api_test.py
  schema.sql
Labels: bug

#82 Add volume to prod database
  docker-compose.yaml
  remote-server/docker-compose.yaml
Labels: documentation, enhancement

#84 Fix user not found and unauthorized
  MinitwitSimulatorAPI/Controllers/TimelineController.cs
Labels: bug

#107 Fix last step in workflow about deploying changes 🔧
  remote-server/deploy.sh
  remote-server/init.sh
Labels: bug

#95 Remove unused controllers in simulator api 🗑️
  MinitwitSimulatorAPI/Controllers/LoginController.cs
  MinitwitSimulatorAPI/Controllers/LogoutController.cs
Labels: enhancement

#96 Remove flag tool code and references 🙅
  .gitignore
  Makefile
  control.sh
  flag_tool.c
Labels: enhancement

#109 Feature/testingworkflow 🧪
  .github/workflows/Testing.yaml
  PythonTests/requirements.txt
Labels: enhancement

#123 Fixed title
  .github/workflows/WeeklyMinorRelease.yaml
Labels: bug

#118 Add Timeline frontend tests⌛
  Minitwit.Tests/IntegrationTests/TimelineTests.cs
  Minitwit.Tests/Utils/MinitwitClientExtensions.cs
  Minitwit/Minitwit.csproj
Labels: enhancement

#126 Add simulator API tests
  Minitwit.Simulator.Api.Tests/Controllers/LatestControllerTests.cs
  Minitwit.Simulator.Api.Tests/Controllers/RegisterControllerTests.cs
  Minitwit.Simulator.Api.Tests/Controllers/TimelineControllerTests.cs
  Minitwit.Simulator.Api.Tests/Minitwit.Simulator.Api.Tests.csproj
  Minitwit.Simulator.Api.Tests/MinitwitSimulatorApiApplicationFactory.cs
  Minitwit.Simulator.Api.Tests/Utils/MinitwitApiHttpClientExtensions.cs
  Minitwit/Minitwit.csproj
  MinitwitSimulatorAPI/Controllers/LatestController.cs
  MinitwitSimulatorAPI/Controllers/TimelineController.cs
  MinitwitSimulatorAPI/MinitwitSimulatorAPI.csproj
  MinitwitSimulatorAPI/Models/FollowerDTO.cs
  MinitwitSimulatorAPI/Models/LatestDTO.cs
  MinitwitSimulatorAPI/Models/MessageDTO.cs
  MinitwitSimulatorAPI/Program.cs
Labels: enhancement

#127 Remove old python code
  .gitignore
  Makefile
  PythonTests/README_Testing.md
  PythonTests/minitwit_scenario.csv
  PythonTests/minitwit_sim_api.py
  PythonTests/minitwit_sim_api_test.py
  PythonTests/minitwit_simulator.py
  PythonTests/minitwit_tests.py
  PythonTests/requirements.txt
  PythonTests/schema.sql
  control.sh
  minitwit.pyc
  static/style.css
  templates/layout.html
  templates/login.html
  templates/register.html
  templates/timeline.html
  tmp/minitwit.db
Labels: enhancement

#134 Bugfix/workflowfix 🌊💦🚣‍♀️🐛
  .github/workflows/AutomaticBuildRelease.Backend.yaml
  .github/workflows/AutomaticBuildRelease.Frontend.yaml
  .github/workflows/Deployment.yaml
  .github/workflows/WeeklyMinorRelease.yaml
  MinitwitSimulatorAPI/MinitwitSimulatorAPI.csproj
Labels: bug

#130 Remove dangerous drop table statements
  schema.sql
Labels: enhancement

#148 Restored testing workflow
  .github/workflows/Testing.yaml
Labels: bug

#147 Update dev container to fit into the new environment
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
  .devcontainer/setup.sh
  Minitwit.Simulator.Api.Tests/MinitwitSimulatorApiApplicationFactory.cs
  Minitwit.Tests/MinitwitApplicationFactory.cs
  README.md
  remote-server/deploy.sh
  remote-server/init.sh
Labels: documentation, enhancement

#150 Add files for prometheus and grafana
  .infrastructure/monitor-server/docker-compose.yaml
  .infrastructure/monitor-server/prometheus.yml
  .infrastructure/remote-server/daemon.json
  .infrastructure/remote-server/deploy.sh
  .infrastructure/remote-server/docker-compose.yaml
  .infrastructure/remote-server/init.sh
  Vagrantfile
Labels: documentation, enhancement

#155 Feature/testing workflow 🧪
  .github/workflows/Testing.yaml
Labels: enhancement

#158 Fix integrations tests by seperating tests data
  Minitwit.Simulator.Api.Tests/Controllers/ControllerTestCollectionDefinition.cs
  Minitwit.Simulator.Api.Tests/Controllers/LatestControllerTests.cs
  Minitwit.Simulator.Api.Tests/Controllers/RegisterControllerTests.cs
  Minitwit.Simulator.Api.Tests/Controllers/TimelineControllerTests.cs
  Minitwit.Simulator.Api.Tests/MinitwitSimulatorApiApplicationFactory.cs
  Minitwit.Tests/IntegrationTests/TimelineTests.cs
Labels: enhancement

#162 Bumped project versions to be current version
  Minitwit/Minitwit.csproj
  MinitwitSimulatorAPI/MinitwitSimulatorAPI.csproj
Labels: bug

#161 Added API tests to the testing workflow
  .github/workflows/Testing.yaml
Labels: bug, enhancement

#153 Bump version of exporter in backend to comply with metric names
  MinitwitSimulatorAPI/MinitwitSimulatorAPI.csproj
Labels: bug

#164 Add open telemetry prometheus endpoint for frontend :eyes:
  Minitwit/Minitwit.csproj
  Minitwit/Program.cs
Labels: enhancement

#182 Corrected workflow
  .github/workflows/AutomaticBuildRelease.Backend.yaml
  .github/workflows/AutomaticBuildRelease.Frontend.yaml
  .github/workflows/Deployment.yaml
Labels: bug

#184 Set up Ansible control node
  .infrastructure/config-management-server/Vagrantfile
  .infrastructure/monitor-server/monitor-playbook.yaml
  .infrastructure/remote-server/web-playbook.yaml
  Vagrantfile
Labels: enhancement

#201 Fix null reference in remove follower
  Minitwit.Infrastructure.Tests/Repositories/FollowerRepositoryTests.cs
  Minitwit.Infrastructure/Repositories/FollowerRepository.cs
Labels: bug

#188 Add async and await to controllers and sql queries
  .gitignore
  Minitwit.Infrastructure.Tests/Repositories/FollowerRepositoryTests.cs
  Minitwit.Infrastructure.Tests/Repositories/LatestRepositoryTests.cs
  Minitwit.Infrastructure.Tests/Repositories/MessageRepositoryTests.cs
  Minitwit.Infrastructure.Tests/Repositories/UserRepositoryTests.cs
  Minitwit.Infrastructure/Repositories/FollowerRepository.cs
  Minitwit.Infrastructure/Repositories/IFollowerRepository.cs
  Minitwit.Infrastructure/Repositories/ILatestRepository.cs
  Minitwit.Infrastructure/Repositories/IMessageRepository.cs
  Minitwit.Infrastructure/Repositories/IUserRepository.cs
  Minitwit.Infrastructure/Repositories/LatestRepository.cs
  Minitwit.Infrastructure/Repositories/MessageRepository.cs
  Minitwit.Infrastructure/Repositories/UserRepository.cs
  Minitwit.Tests/IntegrationTests/LoginAndLogoutTests.cs
  Minitwit.Tests/IntegrationTests/RegisterTests.cs
  Minitwit.Tests/IntegrationTests/SequentialControllerTestDefinition.cs
  Minitwit.Tests/IntegrationTests/TimelineTests.cs
  Minitwit/Controllers/LoginController.cs
  Minitwit/Controllers/RegisterController.cs
  Minitwit/Controllers/TimelineController.cs
  MinitwitSimulatorAPI/Controllers/LatestController.cs
  MinitwitSimulatorAPI/Controllers/RegisterController.cs
  MinitwitSimulatorAPI/Controllers/TimelineController.cs
Labels: enhancement
